sudo: required

services: 
  - docker

before_install:
  - docker build -t karthik530/react-test -f client/Dockerfile.dev client

script:
  - docker run -e CI=true karthik530/react-test npm run test -- --coverage

after_success:
  - docker build -t karthik530/multi-nginx nginx
  - docker build -t karthik530/multi-client client
  - docker build -t karthik530/multi-server server
  - docker build -t karthik530/multi-worker worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push karthik530/multi-nginx:latest
  - docker push karthik530/multi-client:latest
  - docker push karthik530/multi-server:latest
  - docker push karthik530/multi-worker:latest

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-862260549099"
  bucket_path : "docker-multi"
  on:
    branch: "master"
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY