sudo: required

services: 
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # decrypt service-account.json
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # install google cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install kubectl
  - gcloud components update kubectl
  # authenticate google cloud with credentials.json file
  - gcloud auth activate-service-account --key-file service-account.json
  # configure project name to access
  - gcloud config set project multi-k8s-255709
  # configure computation zone to access
  - gcloud config set compute/zone us-central1-a
  # configure cluster to access
  - gcloud container clusters get-credentials multi-cluster
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t karthik530/react-test -f client/Dockerfile.dev client

script:
  - docker run -e CI=true karthik530/react-test npm run test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
