version: '3.7'

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    image: karthik530/custom_nginx
    container_name: nginx
    restart: always
    depends_on:
      - client
      - server
    ports:
      - "4000:80"

  postgres:
    image: postgres
    container_name: postgres

  redis:
    image: redis
    container_name: redis

  server:
    build:
      context: server
      dockerfile: Dockerfile.dev
    image: karthik530/server
    container_name: api
    depends_on:
      - redis
      - postgres
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}

  client:
    build:
      context: client
      dockerfile: Dockerfile.dev
    image: karthik530/client
    container_name: client
    depends_on: 
      - server
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    build:
      context: worker
      dockerfile: Dockerfile.dev
    image: karthik530/worker
    container_name: worker
    depends_on:
      - server
      - redis
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    